// Which deployment this resolver talks to, and nothing else. See ui/src/deployment.ts for
// why the split exists; the same file was shared by both networks until 2026-09-21.
//
// The two files beside this one are generated by `scripts/repoint.mjs`. This one is not.
import { DEPLOYMENT as TESTNET } from './deployment.testnet.ts'
import { DEPLOYMENT as MAINNET } from './deployment.mainnet.ts'

/** `CKB_NETWORK=mainnet` in the environment; everything else is testnet. */
// `globalThis.process` rather than `process`: this file is pulled into the SDK's own
// type-check through an import chain, and that project does not carry node's types.
const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {}
export const DEPLOYMENT = (env.CKB_NETWORK ?? '').toLowerCase() === 'mainnet' ? MAINNET : TESTNET
